### ISSUE TITLE
work on new version SourceMod?

### ISSUE THREAD

**Issue by ghost** [Kailo97/Personal-Weapons#1]
work on new version SourceMod?

**Comment by Kailo97** [comment]
This is not my plugin. This is my decompilation (reproduce source code by smx) of plugin.
No future plans. Code distributed as is.
SM keeps backwards compatibility. You still can install SM 1.11 on server and use this plugin. But you need use compiler from previous SM. Preferred compiler from SM 1.6.

**Comment by ghost** [comment]
L 11/18/2022 - 09:25:16: [SM] Blaming: PW_Bonus.smx
L 11/18/2022 - 09:25:16: [SM] Call stack trace:
L 11/18/2022 - 09:25:16: [SM]   [0] SetFailState
L 11/18/2022 - 09:25:16: [SM]   [1] Line 22, PW_Bonus/file4.sp::Func1516880
L 11/18/2022 - 09:25:16: [SM]   [2] Line 24, C:\Users\BIG\Desktop\Personal-Weapons\cstrike\addons\sourcemod\scripting\PW_Bonus.sp::OnPluginStart
L 11/18/2022 - 09:25:16: [SM] Unable to load plugin "PW_Bonus.smx": Error detected in plugin startup (see error logs)
L 11/18/2022 - 09:25:16: [SM] Exception reported: Configuration "Skins_Weapons" not found
L 11/18/2022 - 09:25:16: [SM] Blaming: PW_FreeWeapons.smx
L 11/18/2022 - 09:25:16: [SM] Call stack trace:
L 11/18/2022 - 09:25:16: [SM]   [0] SetFailState
L 11/18/2022 - 09:25:16: [SM]   [1] Line 24, C:\Users\BIG\Desktop\Personal-Weapons\cstrike\addons\sourcemod\scripting\PW_FreeWeapons.sp::OnPluginStart
L 11/18/2022 - 09:25:16: [SM] Unable to load plugin "PW_FreeWeapons.smx": Error detected in plugin startup (see error logs)
L 11/18/2022 - 09:25:16: [SM] Exception reported: Configuration "Skins_Weapons" not found
L 11/18/2022 - 09:25:16: [SM] Blaming: PW_core_4.smx
L 11/18/2022 - 09:25:16: [SM] Call stack trace:
L 11/18/2022 - 09:25:16: [SM]   [0] SetFailState
L 11/18/2022 - 09:25:16: [SM]   [1] Line 14, PW/file6.sp::Func1679324
L 11/18/2022 - 09:25:16: [SM]   [2] Line 45, C:\Users\BIG\Desktop\Personal-Weapons\cstrike\addons\sourcemod\scripting\PW_core_4.sp::OnPluginStart
L 11/18/2022 - 09:25:16: [SM] Unable to load plugin "PW_core_4.smx": Error detected in plugin startup (see error logs)
L 11/18/2022 - 09:25:16: [SM] Unable to load plugin "PW_Sequences_cracked.smx": Native "EnableWeapon_SkinsWeapons" was not found

**Comment by Kailo97** [comment]
Exception reported: Configuration "Skins_Weapons" not found
This errors because you did wrong installation/configuration of plugin.
Add to addons/sourcemod/configs/databases.cfg Skins_Weapons section with your remote MySQL or use local SQLite.
Like example:
```
	"Skins_Weapons"
	{
  		"driver" 	"sqlite"
  		"host" 	"localhost"
  		"database" 	"skins_weapons"
  		"user" 	"root"
  		"pass" 	"slitpw18"
	}
```
